### ISSUE TITLE
dragend event is fired on click

### ISSUE THREAD

**Issue by matbeard** [w8r/Leaflet.Path.Drag#14]
I'm trying out this plugin to enable dragging of Polylines, but the dragend event is fire on a mouse click even when the line isn't dragged.

This also prevents any bound popups from displaying.

Any suggestions?

**Comment by w8r** [comment]
@matbeard do you still have that problem with the latest version?

**Comment by matbeard** [comment]
Not sure... I've jumped onto a different project for a while. I'll check it out when I get chance and let you know.

**Comment by Shemeikka** [comment]
Hi,

I noticed this same issue. Instead of click-event firing when a circle is clicked, a dragend-event is fired. This prevents popups from showing.

I'm using the the 1.0-branch, Leaflet v1.0.0-rc.1, and Chrome 50.0.2661.102 m.

**Comment by w8r** [comment]
Working on it.

**Comment by w8r** [comment]
hard to solve with the canvas renderer though, since the click events are simulated
