### ISSUE TITLE
Breaking Changes Leaflet Master

### ISSUE THREAD

**Issue by kaynz** [w8r/Leaflet.Path.Drag#15]
Hey,

this Leaflet commit is breaking the dragging of SVG polylines:

https://github.com/Leaflet/Leaflet/commit/0cfe85897fef257d952d1cec5a5a11005fa66da0

Tested with latest Leaflet.Path.Drag release.

Thx :)

**Comment by w8r** [comment]
@kaynz, Hi there! By latest release you mean `1.0.0-beta.2`?

**Comment by w8r** [comment]
Solution is simple though, draggable stuff should have interactive class `.leaflet-interactive`. Very easy to fix. But it's hard to understand the affected version yet

**Comment by kaynz** [comment]
Yes, 1.0.0-beta.2. :)

**Comment by w8r** [comment]
Kewl, wait for `1.0.0-beta.3`)) Btw did you check out the other project I did with rotation and scaling?

**Comment by kaynz** [comment]
Thx ;) Link?

**Comment by w8r** [comment]
[leaflet-path-transform](https://github.com/w8r/Leaflet.Path.Transform)

**Comment by w8r** [comment]
so that css change is going to land in 1.0.0-rc of leaflet? cause currently I have no problem with that

**Comment by kaynz** [comment]
Yea, it should be released into rc soon.
