### ISSUE TITLE
new Leaflet commit breaks dragging

### ISSUE THREAD

**Issue by tehGoti** [w8r/Leaflet.Path.Drag#16]
https://github.com/Leaflet/Leaflet/commit/f05af08a2c1c01fb09ee4fc47ccc568463f96f09

this commit will produce an error when dragging a polygon because the event is undefined (Can't read property _simulated of undefined).

Leaflet.Path.Drag should give the mouse event to that function (see PR)

**Comment by w8r** [comment]
@tehGoti, thanks awfully! glad you found the branch
