### ISSUE TITLE
Version inconsistent

### ISSUE THREAD

**Issue by kennynaoh** [w8r/Leaflet.Path.Drag#18]
Hello @w8r ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
I saw the latest version on git tag is ```v1.0.0-beta.7```, but the latest version on [npm](https://www.npmjs.com/package/leaflet-path-drag) is ```0.1.15```.
Could you publish the latest version on npm?
Thanks very much!

https://github.com/cdnjs/cdnjs/issues/6746

**Comment by w8r** [comment]
@kennynaoh, hi and thanks for reaching out. The version is published on npm as `beta`, since leaflet-1.0 is not the default version yet.
