### ISSUE TITLE
Some thoughts on the pattern

### ISSUE THREAD

**Issue by yohanboniface** [w8r/Leaflet.Path.Drag#19]
So now we basically have:
- on drag: visually drag the feature
- on dragEnd: apply the drag to the feature for real, and let Leaflet redraw it

This has a main drawback: Leaflet is not aware of the change until the dragend. This has been partly workarounded by monkeypatching `getLatLng(s)` methods. But, firstly it's a bit of a hack, and secondly there still are flaws (for example `getCenter` can't be used).

What I understand is that the pattern is that way for performance reasons. But I'm not sure it's worth it: dragging is a manual action.

My suggestion is to sacrifice a bit of performance for a more integrated solution, thus something like:
- on drag: compute matrix, update latlng, asks Leaflet to redraw

I've made some quick tests with https://raw.githubusercontent.com/datasets/geo-countries/master/data/countries.geojson and even dragging a big country like the Russia I can't notice any difference (from a user point of view).

Thoughts?

**Comment by w8r** [comment]
Thoughts in deed!)) I have to try it out and maybe make an option (or make my default solution optional)? That makes sense to be able to have the current latlngs of the path while dragging to do the geo-fencing, but in the usecase I wrote the plugin for the performance cost was really too high. Also IE is firing more `mousemove` events than it can possibly handle itself. I have to do the tests with different type of data.

**Comment by yohanboniface** [comment]
FYI I've made this experiment this morning https://gist.github.com/yohanboniface/ad328f512c3a0d485b2e74a6c95c16b6 in the goal to see if it's worth or not adding path dragging to the core.

**Comment by w8r** [comment]
@yohanboniface So I am still a bit suspicious about unnecessary reprojections, and the cases I have(thousands of points without the ability to simplify + IE) require that to be solved. Are you fine with the idea of making that behaviour optional and the one with reprojection the default one?

**Comment by yohanboniface** [comment]
> Are you fine with the idea of making that behaviour optional and the one with reprojection the default one?

I think that this is absolutely fair for a plugin (given that this is well documented). My concerns are about the code complexity for managing the transform out of Leaflet, and, mainly, that this means desynchronizing the state of the vector and it's visual representation. In other words it a sort of a hack behind Leaflet's back ;)
If we are to integrate path dragging into the core, I don't think that would fit (too much side effects in perspective). But in this case, it also makes more sense to have a plugin that does dragging when extreme performance is required.
That said, last time we discussed integrating path dragging into the core, the overall consensus was more on the negative. So stay on hold ;)

**Comment by w8r** [comment]
Yes, that's what Vladimir told me last year. Ok

**Comment by yohanboniface** [comment]
Pushed a simple version, with a link to this lib in the README for cases where extreme performance is needed: https://github.com/Leaflet/Path.Drag.js

Also made Leaflet.Editable listening for `feature.dragging`, so one could use your lib with Leaflet.Editable and it should work out of the box.

Thanks for you time and feedbacks in this discussion. :)

**Comment by w8r** [comment]
@yohanboniface thanks, looks beautiful! I'll check it with my examples and see what to do next
