### ISSUE TITLE
Support Leaflet-0.8.0-dev and further

### ISSUE THREAD

**Issue by zhujy8833** [w8r/Leaflet.Path.Drag#2]
Hi,
I am currently using Leaflet latest master build (0.8.0-dev), because the in this build it fixes some `FeatureGroup` events issues. 
In my codes, I have a line to call `polygon.editing.enable();` and it will eventually do: 
`L.DomUtil.addClass(this._path._container, 'leaflet-path-draggable');` where `this._path._container` is undefined in this case. I guess `this._path._container` is supposed to be the reference to the `<g>` element which wraps the `<path>`, but for some reasons, this property is gone.
Note that it is working fine in the leaflet stable version (0.7.3)

Thanks.

**Comment by w8r** [comment]
Yep, there's no `._container` thing anymore there. Well, it can be fixed to use `._path` instead, but risky, in case there are already some transforms applied. Maybe it doesn't matter. I'll look into that

**Comment by zhujy8833** [comment]
@w8r Thanks for looking into this. Yea, I think we should stick to `<g>` element here, which is the `_container`, not sure what is the new reference since `_container` is gone. I have inspected a little but didn't find any clues.

**Comment by w8r** [comment]
There are no `<g>` elements in SVG renderer anymore. Structure has changed as well - renderers are gone into separate classes(very good!), - no use putting crutches there to work with both versions, there should be a different implementations. Maybe I'll create a branch for that, as soon as I decide this current thing is stable enough.

**Comment by kaynz** [comment]
Any updates?

**Comment by w8r** [comment]
@kaynz, will try and look into it this weekend

**Comment by kaynz** [comment]
@w8r, thank you! :)

**Comment by w8r** [comment]
@kaynz, the `leaflet-1.0` [branch](https://github.com/w8r/Leaflet.Path.Drag/tree/leaflet-1.0) now works with leaflet-master. Only SVG tested, and there's still no implementation for `Canvas` renderer.

**Comment by kaynz** [comment]
thanks :)
