### ISSUE TITLE
Missing leaflet components lead to errors

### ISSUE THREAD

**Issue by kaynz** [w8r/Leaflet.Path.Drag#21]
Hello @w8r !

The problem mentioned in https://github.com/Leaflet/Leaflet.Editable/issues/83 appears in Leaflet.Path.Drag  and Leaflet.Editable.Drag too, for example:

```
Uncaught TypeError: Cannot read property 'include' of undefined(anonymous function) @ Leaflet.Editable.js:1345(anonymous function) @ Leaflet.Editable.js:17(anonymous function) @ Leaflet.Editable.js:20
L.Path.Drag-src.js:465 Uncaught TypeError: Cannot read property 'prototype' of undefinedwrapMethod @ L.Path.Drag-src.js:465(anonymous function) @ L.Path.Drag-src.js:499(anonymous function) @ L.Path.Drag-src.js:531
L.Editable.Drag-src.js:456 Uncaught TypeError: Cannot read property 'prototype' of undefinedwrapMethod @ L.Editable.Drag-src.js:456(anonymous function) @ L.Editable.Drag-src.js:490(anonymous function) @ L.Editable.Drag-src.js:522
```

**Comment by w8r** [comment]
I am fixing it

Kind regards,
Alexander Milevski

**Comment by w8r** [comment]
i think i got it fixed

**Comment by kaynz** [comment]
Seems to be fixed for Leaflet.Editable.Drag. Leaflet.Path.Drag still breaks - do I really need to include Leaflet.Path.Drag if Leaflet.Editable.Drag is included?

**Comment by w8r** [comment]
`Leaflet.Editable.Drag` includes `Leaflet.Path.Drag`. Alternatively, as I understood from conversation with @yohanboniface, `Leaflet.Editable` now includes a basic dragging functionality, or at least works with https://github.com/Leaflet/Path.Drag.js

**Comment by yohanboniface** [comment]
Leaflet.Editable should work with either Leaflet/Path.Drag.js or this repo, without the need for Leaflet.Editable.Drag, now.
One only needs to include one of those libraries.

**Comment by w8r** [comment]
Yes, I think I'll discontinue this one and put a disclaimer
