### ISSUE TITLE
Path cannot raise click event when map is draggable

### ISSUE THREAD

**Issue by tuspet** [w8r/Leaflet.Path.Drag#22]
Dear @w8r,

In the last submit of the dist/L.Path.Drag-src.js file (commit: 1st of July 2016 branch: leaflet-1.0) there is an issue which should be checked.

The end of the function _onDragEnd contains a new modification: the _fakeStop call (Line 242).

    if (this._mapDraggingWasEnabled) {
      L.DomEvent._fakeStop({ type: 'click' });
      this._path._map.dragging.enable();
    }
	
This means that if the map is draggable then the polygon will never be able to raise a click event.
In our software we need to make both the map and the polygons draggable, and the polygons should be also selectable by simply click on them (show the 'selected polygons' with red color).

If we drag a polygon with mouse no click event should be fired (when releasing the mouse button), but if the polygon was simply clicked (and not moved) we can let the click event to be fired.

(Previously this _fakeStop call was inside an **"if (moved) {...}"** block and this should be also necessary here.)
A very simple "if (moved)" constraint around the _fakeStop can solve this problem.
	
I think the following code should be the correct one:

    if (this._mapDraggingWasEnabled) {
      if (moved) {
        L.DomEvent._fakeStop({ type: 'click' });
      }
      this._path._map.dragging.enable();
    }
	
This block is missing of course both from the src/Path.Drag.js and from the Leaflet.Path.Transform plugin where this Drag plugin is included.

I tested this fix also on touch supported device and it worked.

**Comment by w8r** [comment]
@tuspet good point, thanks!
