### ISSUE TITLE
Touch selection and dragging is problematic together under mobile Chrome versions

### ISSUE THREAD

**Issue by tuspet** [w8r/Leaflet.Path.Drag#26]
Dear @w8r,

I have a problem with the polygon movement on touch devices mainly when using Chrome browsers.
I need to create selectable and draggable rectangles and other polygons. The problem is when touching the screen with fingers, the browser immediately fires Dragging events after the dragstart.
(It seems that Chrome handles the touchmove events very sensitively.)

Unfortunately it is nearly impossible to tap the screen with finger without some pixel movement between touchstart and touchend.

That's why the tapTolerance value was introduced in Leaflet (which is 15 pixel by default) and Leaflet generates a simulated click event when the touch ends and the movement distance is smaller than the tapTolerance value.

Here is the ordered list of the steps that happen:

Step#1. The user starts to touch the screen. -> The _onDragStart function runs.
Step#2. During when the user's finger is seemingly in the same position, the very small 1-2 pixel movement generates an touchmove event causing the _onDrag function to run.
Step#3. Because of the 1-2 pixel movement then immediately the this._path._dragMoved is set to true inside the _onDrag function. (As the Drag plugin does not use the tapTolerance value.)
Step#4. When the user's finger leaves the screen, the leaflet checks whether the tap is valid or not (is inside the tapTolerance, see _isTapValid function)
Step#5. If the movement is smaller than tapTolerance, then leaflet generates a simulated click event.
Step#6. Here comes the problem: the L.DomEvent._fakeStop({ type: 'click' }) function call simply stops the click event.

So now it is very hard to tap on a polygon without any movement, when I try it, I have to tap the screen 30-40 times to finally be able to accidentally quickly tap the screen with 0 pixel movement, (when the 'moved' flag remains false.)

This strange problem is not happening on Firefox, Ipad Safari and on some default android browsers, as these kind of browsers somehow does not create touchmove event immediately when I move my fingers only 1 mm on the screen.

**Solution:**

Fortunately I was able to make a fix which can solve the problem on all browsers an creates a "natural" tapping/dragging feeling:

The following 'if' statement should be inserted in the _onDrag function after the 3rd codeline (after the containerPoint variable creation):

  _onDrag: function(evt) {
    L.DomEvent.stop(evt);
	
    var first = (evt.touches && evt.touches.length >= 1 ? evt.touches[0] : evt);
    var containerPoint = this._path._map.mouseEventToContainerPoint(first);
	
    if (evt.type === "touchmove" && this._path._dragMoved === false) {
        var totalMouseDragDistance = this._dragStartPoint.distanceTo(containerPoint);
        if (totalMouseDragDistance <= this._path._map.options.tapTolerance) {
            return;
        }
    }
    ...

Benefits/Behavior of this 'if' statement:
1. Only has effect when touchmove happens, no effects on using mouse where positioning is much easier.
2. Uses the tapTolerance setting from Leaflet.
3. When the user creates a 'long' movement with the finger (which is more than the tapTolerance, the 'moved' flag will be set to true later in the _onDrag function) even if the user pulls back the finger more-or-less into the original position no click event will be fired. (So a long movement is considered as a "real move", not just a click [regardless the position where the touch ends.])
4. Browser independently you can both tap(click) on a shape and both drag them to an other position easily.

The devices and browsers where I tested my fix:

1. PC (only with mouse of course)
- Firefox: the fix does not affect dragging/selecting when mouse is used
- Chrome: the fix does not affect dragging/selecting when mouse is used
- IE11: the fix does not affect dragging/selecting when mouse is used

2. Ipad
- Safari: OK
- Chrome: OK only with the new fix

3. Samsung Galaxy Android tablet: 
- Firefox: OK
- Chrome: OK only with the new fix
- Internal browser: OK only with the fix (it was almost impossible the select a polygon on this browser type before)

4. LG Android (Full HD) phone:
- Firefox: OK
- Chrome: OK only with the new fix (It was very hard to select a polygon)
- Internal Browser: OK

Feel free to comment this solution. I think this can be an easy solution to be inserted into the plugin.
We especially need it in the Transform plugin, but the root cause is here in the Drag plugin.

**Comment by w8r** [comment]
@tuspet thank you so much for your comment and detailed explanation. I will try out your solution!

**Comment by tuspet** [comment]
Dear @w8r,

thank you for quickly creating the new release with the fix.
Just a question: do you plan (or when do you plan) to include the latest version of Drag plugin in the Transform Plugin?

**Comment by w8r** [comment]
Thanks for the provided solution! I will have to introduce 2 new versions of L.Transform plugin then(because of breaking changes with canvas renderer), same as I did here - for `leaflet@<1.0.2` and `leaflet@^1.0.2` and test them

**Comment by tuspet** [comment]
Dear @w8r,

as we are very close to release the next version of our software it would be good to have this touch-fix via npm package in the Transform plugin.
As the dist/L.Path.Transform-src.js and the dist\L.Path.Transform.js directly includes the (previous version) code of the drag plugin we cannot have the touch-fix just by referencing the actual (latest) transform plugin.

Can you please create a new leaflet-path-transform npm package? (If it is not possible now, we can hack this fix into the code on our side, but the most proper way would be just include the new npm package.)

Thank you for your answer!
