### ISSUE TITLE
Is there a way to drag multiple geometries?

### ISSUE THREAD

**Issue by fnicollet** [w8r/Leaflet.Path.Drag#3]
Hello and thanks for that useful library,

I am able to move single geometries with no problem. Now I would like to be able to have a selection of  geometries and if I drag one, it drags them all (with the same offset).
I am able to "create a selection" (basically, I have an array of Path) and each has a Leaflet.Path.Drag but when I drag one, only that one is moving, because the event listeners are reacting only to the attached path.
What is your advice on this? Should the library go further and implement this or should I try to "sync" multiple Leaflet.Path.Drag behing the scene?

Thanks,
Fabien

**Comment by fnicollet** [comment]
In the end, found an easy way to sync it. Registrer to the "drag" event and _applyTransform with the same matrix to the other shapes. Also registrer to "dragend" and mimic the behaviour of the dragend handler on other shapes

**Comment by w8r** [comment]
:+1:

**Comment by Harvinator** [comment]
Thanks @fnicollet using your suggestion I got this to work for a geoJson feature group. Here's the code that I used.

```

var geoJsonFeatureGroup = L.geoJSON(geoJson, {
	onEachFeature: function (feature, layer)
	{
		// I also needed to handle GeometryCollections so that's what the instanceof L.LayerGroup is for.
		if (layer instanceof L.LayerGroup)
		{
			layer.eachLayer(__initDraggableLayer);
		} else
		{
			__initDraggableLayer(layer);
		}
	}
});
function __initDraggableLayer(layer)
{
	layer.makeDraggable();
	layer.dragging.enable();

	layer.on('drag', function (dragEvent)
	{
		// Registrer to the "drag" event and _applyTransform with the same matrix to the other shapes. 
		geoJsonFeatureGroup.getLayers().forEach(function (otherLayer)
		{
			if (otherLayer instanceof L.LayerGroup)
			{
				otherLayer.eachLayer(function (otherSubLayer) { __dragTransform(layer, otherSubLayer) });
			}
			else
			{
				__dragTransform(layer, otherLayer);
			}
		});
	});
	layer.on('dragend', function ()
	{
		// Also registrer to "dragend" and mimic the behaviour of the dragend handler on other shapes
		geoJsonFeatureGroup.getLayers().forEach(function (otherLayer)
		{
			if (otherLayer instanceof L.LayerGroup)
			{
				otherLayer.eachLayer(function (otherSubLayer) { dragDropTransform(layer, otherSubLayer) });
			}
			else
			{
				dragDropTransform(layer, otherLayer);
			}
		});
	});
}

function __dragTransform(layer, otherLayer)
{
	if (otherLayer != layer && otherLayer._transform)
	{
		otherLayer._transform(layer.dragging._matrix);
	}
}
function dragDropTransform(layer, otherLayer)
{
	if (otherLayer != layer
		&& otherLayer.dragging
		&& otherLayer.dragging._transformPoints)
	{
		otherLayer.dragging._transformPoints(layer.dragging._matrix);
		otherLayer._updatePath();
		otherLayer._project();
		otherLayer._transform(null);
	}
}
```

**Comment by w8r** [comment]
I will add it to the docs

**Comment by mikila85** [comment]
is there an easy way to do this for multiple markers? i have 5 markers on map, 3 of them selected. and want to drag them together, any easy way?

**Comment by peteszym** [comment]
Thanks @fnicollet and @Harvinator for setting me on the right track, but have you guys been able to do the same thing for a marker? I want to create a drag handler icon above my polygon shape, and your method works great for everything except a marker, because markers don't seem to use a matrix transformation that can directly be applied to a polygon in the same way. Have you guys dealt with this sort of thing before?

**Comment by w8r** [comment]
can you use circle markers?

**Comment by peteszym** [comment]
Circle markers don't take icon definitions just the same, as far as I can see in the docs. What I ended up doing was embedding the icon on the page as an SVG
```
        <svg width="0" height="0" style={{display:'block'}}>
          <defs>
            <pattern id="move_icon" width="100%" height="100%" x="0" y="0" viewBox="0 0 20 20">
              <image width="20" height="20" xlinkHref={moveIcon} preserveAspectRatio="xMidYMid slice" />
            </pattern>
          </defs>
        </svg>
```
then created a basic L.circle with a class attribute name, and finally targeted it with CSS with `fill: url(#move_icon);` Seems to get me where I need.

**Comment by FloMueh** [comment]
Hey guys,

is there anything new for moving multiple markers at once? 
Would be great to hear from you!

kind regards

**Comment by teatalay** [comment]
> In the end, found an easy way to sync it. Registrer to the "drag" event and _applyTransform with the same matrix to the other shapes. Also registrer to "dragend" and mimic the behaviour of the dragend handler on other shapes

could you share your example please?
