### ISSUE TITLE
Undo dragging

### ISSUE THREAD

**Issue by jjalan** [w8r/Leaflet.Path.Drag#34]
Is there a way to undo a drag?

Ex: User moves the object to an invalid location in which case object is put back at its original location.

**Comment by jjalan** [comment]
This is what I am doing at dragend if to revert the move:

```
var layer = e.target;
var matrix = layer.dragging._matrix;
matrix[4] = -matrix[4];
matrix[5] = -matrix[5];
layer.dragging._transformPoints(matrix);
layer._updatePath();
layer._project();
layer._transform(null);
```

It seems to be working, only issue the new position is not updated. User have to manually interact wit the map (say zoom out) in order to see object at its old position.

**Comment by w8r** [comment]
Just store the coordinates at the 'dragstart' event and revert to it on
`dragend`. That's what I would do. It would even skip unnecessary
calculations. Vector layers have setLatLngs methods
