### ISSUE TITLE
Values not updating on target on event drag

### ISSUE THREAD

**Issue by perseus086** [w8r/Leaflet.Path.Drag#37]
I need to get the center of a rectangle while dragging.

I've tried the following:
```
var rectangle = new L.Rectangle([...], { draggable: true }).addTo(map);
//Copy from here
rectangle.on('drag', function(event){
   console.log('on drag', event.target.getCenter());
})

rectangle.on('dragend', function(event){
   console.log('on dragend', event.target.getCenter());
})
```

On **dragend** it works. But on **drag** it is not working.

Problem appears with polyline, polygon and rectangle.

We can reproduce the issue by adding previous lines (from comment //Copy from here) on console of the browser here: http://w8r.name/Leaflet.Path.Transform/example/ and moving the rectangle.

**Comment by artuska** [comment]
+1, same issue here :(

**Comment by w8r** [comment]
That's the point of this library, it doesn't do reprojections while dragging, hence preserves the performance.

https://github.com/w8r/Leaflet.Path.Drag/blob/master/src/Path.Drag.js#L296
