### ISSUE TITLE
is there a way to drag multiple markers

### ISSUE THREAD

**Issue by FloMueh** [w8r/Leaflet.Path.Drag#40]
Hi guys, 

i have read #3 about moving multiple geometries. But i have to move multiple Markers. Is there now an easy way to solve this? 

I have the marker added to an layerGroup and want to move each marker when one marker is moved. The Solution form @Harvinator is not working this way cause the markers doesn't have applyTransform method and matrix properties. 

Thank for advice.

**Comment by FloMueh** [comment]
found a solution. i calculate the shift via the old marker pos.

**Comment by ubaiy** [comment]
> found a solution. i calculate the shift via the old marker pos.

Hello @FloMueh I also want to do the same I have multiple markers inside one polygon and want to move only selected markers at the same time
