### ISSUE TITLE
Dragging multiple react leaflet's GeoJSONs

### ISSUE THREAD

**Issue by AndrejGajdos** [w8r/Leaflet.Path.Drag#46]
Hi there,

Thanks for this great library. I am trying to implement dragging multiple GeoJSON in react-leaflet, but I am struggling to apply `_transform` method to multiple GeoJSONs objects. I think the issue is that `_transform` method is not applied to correct layers, but I have no idea if this is an issue of react-leaflet, this library or I do something wrong.

Here is a [codesandbox](https://codesandbox.io/s/green-pine-5xty6?file=/src/App.js).

**Comment by w8r** [comment]
@AndrejGajdos I cannot seem to get the codesandbox to work - `MapContainer` is `undefined`

**Comment by w8r** [comment]
Does this make sense? https://codesandbox.io/s/condescending-noyce-uoblt?file=/src/App.js

**Comment by AndrejGajdos** [comment]
@w8r thanks for replying. Yes, your codesandox is correct and you can see the issue there.

It's strange you get error message `MapContainer is undefined` in my codesandbox. When I open it, its working. I was trying other `react-leaflet` versions. Versions `3.x.x` have `MapContainer` and versions `2.x.x` have `Map` component instead.

**Comment by w8r** [comment]
Sorry for being so slow, but can you ple  explain the issue? The polygons are draggable, do you want to group them differently?

Kind regards,
Alexander Milevski

**Comment by AndrejGajdos** [comment]
@w8r sorry, I didn't explain my issue well. If you drag green polygon, all polygons should move together, not only the dragged polygon.

**Comment by AndrejGajdos** [comment]
Sorry, my bad. Fix is [here](https://stackoverflow.com/a/65902312/968379).
