### ISSUE TITLE
Leaflet.Path.Drag does not work on multi-geometries, such as Multipolygon

### ISSUE THREAD

**Issue by fnicollet** [w8r/Leaflet.Path.Drag#5]
Hello,

Your library doesn't seem to work on Multipolygons as it only takes one layer (path) while a multipolygon is composed of multiple layers. It would be nice for it to work on L.FeatureGroup objects as well.

I believe it would be a good addition to the library making it easier to use out-of-the-box

If you need sample data, the one from the leaflet example is a good start (campus):
http://leafletjs.com/examples/geojson.html

Fabien

**Comment by w8r** [comment]
Ok, I get it. I'll try

**Comment by w8r** [comment]
@fnicollet, done. Probably not in the prettiest way code-wise, but I wouldn't like to affect `L.FeatureGroup` class at this time. Check out the demo, I added a couple of MultiPolys
