### ISSUE TITLE
Depending on the zoom level when dragging, the feature gets simplified

### ISSUE THREAD

**Issue by fnicollet** [w8r/Leaflet.Path.Drag#6]
Hello,

I have noticed that the lib works well unless leaflet already reduced the number  of points of the geometry because it too small.
Can be reproduced on  the example:
http://w8r.github.io/Leaflet.Path.Drag/example/
This is the original feature:
![image](https://cloud.githubusercontent.com/assets/1240481/6327125/c2f0f520-bb58-11e4-9fa7-7f8009413f1d.png)

Unzoom and move the feature:
![image](https://cloud.githubusercontent.com/assets/1240481/6327131/d758e55e-bb58-11e4-9f81-0dfccd1df0e2.png)

Zoom back in:
![image](https://cloud.githubusercontent.com/assets/1240481/6327142/ea4ab700-bb58-11e4-89d4-51ec9621663c.png)

The feature has been simplified but it shouldn't. The library probably transforms the points while they have already been simplified by leaflet's internals and then set them as the original ones

Fabien

**Comment by fnicollet** [comment]
Narrowed down the issue. It comes from the fact that  you work in pixel space in the _transformPoints function. So basically, it is rounded to the closest pixel, which is fine unless your polyon is far away.
Transformations should always happen in projected coordinates space.

**Comment by w8r** [comment]
Good point

**Comment by w8r** [comment]
the problem is that the transformation matrix is in pixels

**Comment by fnicollet** [comment]
Exactly, everything is calculated from pixels. It is good for the SVG
matrix but not for the points.

I changed that in my code (not using your lib) to accept any matrix so that
I can do scale and rotate as well, you probably need to do something similar

On Fri, Feb 27, 2015 at 12:11 PM, Alexander Milevski <
notifications@github.com> wrote:

> the problem is that the transformation matrix is in pixels
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w8r/Leaflet.Path.Drag/issues/6#issuecomment-76378466>.
>



-- 
Fabien Nicollet
Tel : +33 (0)6 60 54 72 20

**Comment by w8r** [comment]
Haven't really solved it for the general case, I refrained using matrices in final transformation for now, because working with 2 matrices(transformed and untransformed) would bloat the method and there's no use for that now. but I think I'll revisit that if I'll be using it for scaling and rotating.

**Comment by fnicollet** [comment]
I see, thanks for your work. In my case, i needed the topology to be conserved so I am working with 2 matrices (a px one for the dragging so that the preview is fast and a meter one for the dropping, to correctly transform the points.
I also needed to scale, rotate, select multiple geometries and undo/redo so i had to completly change your project in the end. I guess it might be better if this lib stays minimal

Fabien

**Comment by w8r** [comment]
>  a px one for the dragging so that the preview is fast and a meter one for the dropping, to correctly transform the points

same here, I just don't use the whole matrix, just `tx` and `ty` values. And I couldn't use meters, since the default `L.CRS.EPSG3857` is inconsistent in its use of meters(it skips them in inverse projection). Not a thing I would want to touch for the task like that.
