### ISSUE TITLE
Leaflet 1.9?

### ISSUE THREAD

**Issue by tap2k** [w8r/Leaflet.Path.Drag#64]
Does this work with Leaflet v 1.9? I cant get it to work like the example.

**Comment by w8r** [comment]
https://github.com/w8r/Leaflet.Path.Drag/assets/26884/02b4186f-6291-48ef-b109-561d81ff3e01

I see no issue with `leaflet@1.9.4`

Can you give me some more details?

**Comment by Intros66** [comment]
https://github.com/user-attachments/assets/d83a1031-c4a4-4274-87b2-e9a7d636f770

`leaflet@1.9.4`
`leaflet-editable@1.3.0`

**Comment by w8r** [comment]
Closing this then
