### ISSUE TITLE
Enable/Disable dragging on the fly

### ISSUE THREAD

**Issue by ADXBA** [w8r/Leaflet.Path.Drag#9]
Hi is there a way to enable or disable the drag capability of a marker on the fly? I've noticed an enabled property in the event handlers (data.target.dragging.enabled), but can't find the property in the standard marker instance.

Thanks

**Comment by w8r** [comment]
@ADXBA, Marker? What do you mean? `CircleMarker`?

**Comment by w8r** [comment]
The API is the same as for the `L.Marker`. You can try that out on the [demo page](http://w8r.github.io/Leaflet.Path.Drag/example/)
```js
map.eachLayer(function(l) { 
  if (l instanceof L.CircleMarker) { 
    l.dragging.enable();
  }
});
```
That will disable the dragging for the small blue `CircleMarker`

**Comment by ADXBA** [comment]
Perfect, thanks for that!
